/****************************************************************
 Name: ApplicationDataPopulatorInterface
============================================================
Author: 
Purpose: Interface for ApplicationDataPopulator
============================================================

****************************************************************/

public interface ApplicationDataPopulatorInterface {

	void populateDataOnNewApplications(List<Application__c> applications);
}