/****************************************************************
 Name:  ApplicationAutoDeclineJSON
============================================================
Author: Lenny
Purpose: JIRA#1476
JSON Structure for Application Auto Decline Callout
to notify DLAP.
============================================================

****************************************************************/

public with sharing class ApplicationAutoDeclineJSON {
	//public class ApplicationAutoDeclineRequest {
	//	public String applicationNumber;
	//	public String autoDeclineStatus;
	//	public Datetime autoDeclineDate;
	//	public Datetime submittedDate;
	//}

	//public class ApplicationAutoDeclineResponse {}
}