/****************************************************************
 Name: ChecklistItemGeneratorInterface
============================================================
Author: Lenny
Purpose: Interface for ChecklistItemGenerator
============================================================

****************************************************************/

public interface ChecklistItemGeneratorInterface {

	void handleChecklistGeneration(List<SObject> sObjects);
}