/****************************************************************
 Name: ChecklistItemUpdaterInterface
============================================================
Author: Lenny
Purpose: Interface for handling ChecklistItems
============================================================

****************************************************************/

public interface ChecklistItemUpdaterInterface {

	void handleChecklistUpdates(List<SObject> sObjects);
}