/****************************************************************
 Name: ClosingDocumentsGenerator
============================================================
Author: 
Purpose: Class for closing documents generator
============================================================

****************************************************************/

public with sharing class ClosingDocumentsGenerator implements ClosingDocumentsGeneratorInterface {
	
	public ClosingDocumentsGenerator(){}

	public void generateClosingDocuments(List<Case> cases){
		
	}
}