/****************************************************************
 Name: ClosingDocumentsGeneratorInterface
============================================================
Author: 
Purpose: Interface for ClosingDocumentsGenerator
============================================================

****************************************************************/

public interface ClosingDocumentsGeneratorInterface {

	void generateClosingDocuments(List<Case> cases);
}