/****************************************************************
 Name: ContentDocumentLinkCleanerInterface
============================================================
Author: 
Purpose: Interface for ContentDocumentLinkCleaner
============================================================

****************************************************************/

public interface ContentDocumentLinkCleanerInterface {
    void processDocumentLinks(List<ContentDocumentLink> contentDocumentLinks);
}