/****************************************************************
 Name:  DisbursementLineItemDAO
============================================================
Author: Matt
Purpose: Interface for Disbursement Line Items                                                                                                 
============================================================

****************************************************************/
public interface DisbursementLineItemDAO {
	void insertDisbursementLineItems(List<Disbursement_Line_Item__c> disbursementLineItems);
}