/****************************************************************
 Name:  DocumentLineItemDataAccessorMock
============================================================
Author: Lenny
Mock Data Accessor for Document_Line_Items__c object
============================================================

****************************************************************/
/*DELETED ONCE ON BITBUCKET*/
@isTest
public with sharing class DocumentLineItemDataAccessorMock implements DocumentLineItemDAO {

	//public Integer insertDocumentLineItemsCallCount { get; private set; }

	//public DocumentLineItemDataAccessorMock(){
	//	insertDocumentLineItemsCallCount = 0;
	//}

	//public void insertDocumentLineItems(List<Document_Line_Items__c> docLineItems){
	//	insertDocumentLineItemsCallCount++;
	//}
}