/****************************************************************
 Name:  DocumentLineItemDataAccessor
============================================================
Author: Lenny
Data Accessor for Document_Line_Items__c object
============================================================

****************************************************************/
/*DELETED ONCE ON BITBUCKET*/
public with sharing class DocumentLineItemDataAccessor implements DocumentLineItemDAO {

	//public DocumentLineItemDataAccessor(){}

	//public void insertDocumentLineItems(List<Document_Line_Items__c> docLineItems){
	//	insert docLineItems;
	//}
}