/****************************************************************
 Name: DocumentChecklistGeneratorInterface
============================================================
Author: Kevin
Purpose: Interface for DocumentChecklistGenerator
============================================================

****************************************************************/

/*DELETED ONCE ON BITBUCKET*/
public interface DocumentChecklistGeneratorInterface {

    //void handleDocumentGeneration(List<Case> cases);
}