/****************************************************************
 Name: DocumentLineItemDAO
============================================================
Author: 
Purpose: Data Access Object for Document_Line_Items__c
============================================================

****************************************************************/
/*DELETED ONCE ON BITBUCKET*/
public interface DocumentLineItemDAO {
	//void insertDocumentLineItems(List<Document_Line_Items__c> docLineItems);
}