/****************************************************************
 Name: DocumentChecklistDAO
============================================================
Author: 
Purpose: Data Access Object for Document_Checklist__c
============================================================

****************************************************************/

/*DELETED ONCE ON BITBUCKET*/
public interface DocumentChecklistDAO {
	//Document_Checklist__c getDocumentChecklistByLoanConditionCode(String loanConditionCode);
}