/****************************************************************
 Name: DocumentChecklistDataAccessorMock
============================================================
Author: 
Purpose: Mock Data Access for Document_Checklist__c
============================================================

****************************************************************/
/*DELETED ONCE ON BITBUCKET*/
@isTest
public with sharing class DocumentChecklistDataAccessorMock implements DocumentChecklistDAO {
	//public Integer getDocumentChecklistByLoanConditionCodeCallCount {get; private set;}

	//public Document_Checklist__c getDocumentChecklistByLoanConditionCodeReturn;

	//public DocumentChecklistDataAccessorMock(){
	//	getDocumentChecklistByLoanConditionCodeCallCount = 0;

	//	getDocumentChecklistByLoanConditionCodeReturn = new Document_Checklist__c();
	//}

	//public Document_Checklist__c getDocumentChecklistByLoanConditionCode(String loanConditionCode) {
	//	getDocumentChecklistByLoanConditionCodeCallCount++;
	//	return getDocumentChecklistByLoanConditionCodeReturn;
	//}
}