/****************************************************************
 Name: ApplicationDAO
============================================================
Author: Sahil Grover
Purpose: Generic Exception class for Query.cls
============================================================

****************************************************************/

public with sharing virtual class DynamicQueryException extends Exception {

}