/****************************************************************
 Name:  EventRequestStageUpdateHandlerInterface
============================================================
Author: Lenny
Purpose: Interface for EventRequestStageUpdateHandler.
============================================================

****************************************************************/
public interface EventRequestStageUpdateHandlerInterface {

	void processEventRequest(List<Event_Request__c> eventRequests);
}