@isTest
private class LOR_AuraServiceTest
{
	@isTest
	static void getApplicationById_givenInvalidId_shouldThrowException(){

	}

	@isTest
	static void getApplicantsAndRelatedContactsByApplicationId_givenInvalidId_shouldThrowException(){

	}

	@isTest
	static void getLoansByApplicationId_givenInvalidId_shouldThrowException(){

	}

	@isTest
	static void getDisasterById_givenInvalidId_shouldThrowException(){

	}

	@isTest
	static void getDamagedPropertiesAndLossVerificationsByApplicationId_givenInvalidId_shouldThrowException(){

	}

	@isTest
	static void getAssetIncomesByApplicationId_givenInvalidId_shouldThrowException(){

	}

	@isTest
	static void getIRSTranscriptsByApplicationId_givenInvalidId_shouldThrowException(){

	}

	@isTest
	static void getPicklistOptions_givenValidObjectNameAndPicklistFieldName_shouldReturnListOfOptions(){

	}

	@isTest
	static void getPicklistOptions_givenValidObjectNameAndNonPicklistFieldName_shouldReturnEmptyList(){

	}
}