/****************************************************************
 Name: QuerySupportException
============================================================
Author: Sahil Grover 
Purpose: Exception indicating a feature or function is not supported
============================================================

****************************************************************/

public with sharing class QuerySupportException extends DynamicQueryException {

}